name: Automated Code Quality

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, dom, filter, gd, iconv, json, mbstring, pdo
        
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
          
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
      
    - name: Run Phixer (dry run)
      run: composer fix:dry
      
    - name: Run PHPStan
      run: composer analyse
      
    - name: Run Tests
      run: composer test
      
    - name: Auto-fix code style issues
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        composer fix:style
        if [ -n "$(git status --porcelain)" ]; then
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "style: auto-fix code style issues [skip ci]"
          git push
        fi
        
  security-check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'
        
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
      
    - name: Run security check
      run: |
        composer audit --no-dev
        
    - name: Check for vulnerabilities
      uses: symfonycorp/security-checker-action@v5
